# Pràctica amb programació numèrica

In [1]:
# Import numpy as np
import numpy as np
# Import numpy random to create random arrays
from numpy import random

## Nivell 1

### Exercici 1

Crea una funció que donat un Array d’una dimensió, et faci un resum estadístic bàsic de les dades. Si detecta que l’array té més d’una dimensió, ha de mostrar un missatge d’error.

In [2]:
def array_stats(array):
    if array.ndim > 1:
        print("The array should have no more than one dimension")
    else:
        print("Data: {}".format(array))
        print("Num dimensions: {}".format(array.ndim))
        print("Shape: {}".format(array.shape))
        print("Num of items: {}".format(len(array)))
        print("Sum: {}".format(array.sum()))
        print("Mean : {}".format(array.mean()))
        print("Std Variation: {}".format(array.std()))
        print("Variance: {}".format(array.var()))
        print("Minimum value: {}".format(array.min()))
        print("Maximum value: {}".format(array.max()))

In [3]:
# Array of more than one dimension. The function shows an error message
array_2d = np.array([[1,2], [3,4]])
array_stats(array_2d)

The array should have no more than one dimension


In [4]:
# Array of one dimension
size = random.randint(10,20)
array = random.randint(50, size=size)
array_stats(array)

Data: [48 18  7 29 14 34  8 42 49 29 43]
Num dimensions: 1
Shape: (11,)
Num of items: 11
Sum: 321
Mean : 29.181818181818183
Std Variation: 14.837410836482844
Variance: 220.1487603305785
Minimum value: 7
Maximum value: 49


### Exercici 2

Crea una funció que et generi un quadrat NxN de nombres aleatoris entre el 0 i el 100.

In [5]:
# Function to create a NxN array with random numbers between 0 and 100
def array_creation(num_cols_rows):
    array = np.random.randint(0, 100, size=(num_cols_rows, num_cols_rows))
    return array

In [6]:
# Variable to store the number of rows and columns. It´s passed as argument to the function that creates the array
rows_cols = 10
arr = array_creation(rows_cols)
print(arr)

[[25 14 64 35  3 74 24 30 77 81]
 [33 76 49 52 80 98 18 61 34  7]
 [92 45 66 40 47 19 13 78 74 23]
 [60  3  1 13 13 60 28 88 66 36]
 [20 68 60 85 64 30 85 36 51 45]
 [50 89  1 36 71  9 52 92 71 62]
 [97 44 29 38 23 46 81 62 86  9]
 [42 73 64 36 92 82 56 42  3 11]
 [61 46 41 35 60 80 93 17 10 14]
 [66 68 39 46 40 50 13 74 60 41]]


### Exercici 3

Crea una funció que donada una taula de dues dimensions, et calculi els totals per fila i els totals per columna. 

In [7]:
new_array = np.random.randint(0, 100, size=(5, 5))
print(new_array)

[[49 39  8 56 23]
 [45 49  4 33 67]
 [81  5 94  2 26]
 [41 42 37 81 63]
 [94 10 43 30 80]]


In [8]:
# Funtion that sums row and col sums. Returns a tuple (sum rows array, sum cols array)
def sum_row_col(array):
    sum_row = array.sum(axis=1)
    sum_col = array.sum(axis=0)
    return sum_row, sum_col

In [9]:
# Funtion to show the total sums
def show_sums(row, col):
    message = "Total rows sum\n==============\n"
    for index, elem in enumerate(row):
        message += "Row {}: {}\n".format(index + 1, elem)
    message += "\nTotal cols sum\n==============\n"
    for index, elem in enumerate(col):
        message += "Col {}: {}\n".format(index + 1, elem)
    print(message)

In [10]:
# Unpack the tuple
row, col = sum_row_col(new_array)
# Call to show_sums function
show_sums(row, col)

Total rows sum
Row 1: 175
Row 2: 198
Row 3: 208
Row 4: 264
Row 5: 257

Total cols sum
Col 1: 310
Col 2: 145
Col 3: 186
Col 4: 202
Col 5: 259



### Exercici 4

Implementa manualment una funció que calculi el coeficient de correlació. Informa’t-en sobre els seus usos i interpretació.

Correlation coefficient formulas are used to find how strong a relationship is between data. The formulas return a value between -1 and 1, where:

* 1 indicates a strong positive relationship.
* -1 indicates a strong negative relationship.
* 0 indicates no lineal relation between the variables.

The correlation coefficient formula that I'm going to use is this:

$r=\huge{\frac{\sum\left[\left(x_i-\overline{x}\right)\left(y_i-\overline{y}\right)\right]}{\sqrt{\mathrm{\Sigma}\left(x_i-\overline{x}\right)^2\ 
\ast\ \mathrm{\Sigma}(y_i\ -\overline{y})^2}}}$

#### Example of a strong correlated data

In [11]:
# Create two arrays for the variables X and Y
X = np.arange(0,20,2, dtype=float)
Y = np.arange(0,40,4, dtype=float)
print("X: {}".format(X))
print("Y: {}".format(Y))

X: [ 0.  2.  4.  6.  8. 10. 12. 14. 16. 18.]
Y: [ 0.  4.  8. 12. 16. 20. 24. 28. 32. 36.]


#### Calculate the mean of each variable

$\Large{\overline{x}\quad\overline{y}}$

In [12]:
X_mean = X.mean()
Y_mean = Y.mean()
print("Mean X: {}".format(X_mean))
print("Mean Y: {}".format(Y_mean))

Mean X: 9.0
Mean Y: 18.0


#### Substract the mean to every single variable
$\Large{\left(x_i-\overline{x}\right)\left(y_i-\overline{y}\right)}$

In [13]:
X -= X_mean
Y -= Y_mean
print("X: {}".format(X))
print("Y: {}".format(Y))

X: [-9. -7. -5. -3. -1.  1.  3.  5.  7.  9.]
Y: [-18. -14. -10.  -6.  -2.   2.   6.  10.  14.  18.]


#### Calculate the numerator of the equation

$\Large{\sum\left[\left(x_i-\overline{x}\right)\left(y_i-\overline{y}\right)\right]}$

In [14]:
numerator = np.sum(X * Y)
print(numerator)

660.0


#### Calculate de denominator
$\Large{\sqrt{\mathrm{\Sigma}{(x_i\ -\ \overline{x})}^2\ \ast\ \mathrm{\Sigma}(y_i\ -\overline{y})^2}}$

In [15]:
denominator = np.sqrt(np.sum(np.power(X, 2)) * np.sum(np.power(Y, 2)))
print(denominator)

660.0


#### Calculate r value dividing the numerator by the denominator
$r=\Large{\frac{\sum\left[\left(x_i-\overline{x}\right)\left(y_i-\overline{y}\right)\right]}{\sqrt{\mathrm{\Sigma}\left(x_i-\overline{x}\right)^2\ 
\ast\ \mathrm{\Sigma}(y_i\ -\overline{y})^2}}}$

In [16]:
r = numerator / denominator
print("r value is {}. This indicates a strong positive relationship".format(r))

r value is 1.0. This indicates a strong positive relationship


***
### Function to calculate the correlation coeficient

Now I'm going to define a function to calculate the correlation coeficient and try it with random arrays

In [17]:
# The function takes two arrays (X,Y) and calculates r
def correlation_coef(X, Y):
    # mean of X and Y
    X_mean = X.mean()
    Y_mean = Y.mean()
    
    # Mean substraction
    X -= X_mean
    Y -= Y_mean
    
    # Numerator
    numerator = np.sum(X * Y)
    
    # Denominator
    denominator = np.sqrt(np.sum(np.power(X, 2)) * np.sum(np.power(Y, 2)))
    
    # Correlation coeficient
    r = numerator / denominator
    
    return r    

In [18]:
# Create two arrays for the variables X and Y with random values
X = np.random.rand(20)
Y = np.random.rand(20)
print("X: {}\n".format(X))
print("Y: {}\n".format(Y))
print("r = {}\n".format(correlation_coef(X,Y)))

X: [0.83166116 0.35956173 0.19578202 0.06909524 0.33818721 0.54531264
 0.4772176  0.99161181 0.03966059 0.98194371 0.18184938 0.00723653
 0.56396932 0.57001204 0.96306508 0.15828444 0.61193495 0.85766875
 0.04771002 0.61546741]

Y: [0.72749359 0.66799313 0.66046168 0.83585033 0.04596374 0.12373894
 0.65750609 0.09446775 0.03200114 0.68278674 0.59627281 0.49045244
 0.61893717 0.24987564 0.10199735 0.55401938 0.72746388 0.73662214
 0.29418033 0.41299316]

r = -0.029264497661201153



In [19]:
# Create two arrays for the variables X and Y with random values
X = np.random.normal(size=20)
Y = np.random.normal(size=20)
print("X: {}\n".format(X))
print("Y: {}\n".format(Y))
print("r = {}\n".format(correlation_coef(X,Y)))

X: [ 0.36687713  1.78525316  0.00393206  0.07970207 -1.24099192 -1.40613601
  1.39188759  0.28920493  1.4063934   0.51026489  0.76986339 -0.7576108
 -1.0442752  -0.58515651  0.24104731 -1.31652444 -0.24383251 -0.94836443
 -0.08005872 -0.90060247]

Y: [ 1.19868465 -0.20697547  0.15183626 -0.59381121 -0.44207993  0.0664527
 -0.7272723  -0.97736987  1.56469013 -1.27227554  0.47784536  0.70020085
 -0.36936567 -1.17724691  1.27877744  0.40187678  1.68100629  0.35361995
  0.48644242 -0.83475242]

r = 0.0949985712704152

